// Minimal parser for `.resw` files (ResX XML).
//
// The format generated by the ResX/Crowdin tooling is very regular:
//
//   <data name="Key" xml:space="preserve">
//     <value>Text</value>
//     <comment>optional</comment>
//   </data>
//
// This module is deliberately self-contained (no dependencies) since it's
// shared between `build.rs` (via `include!`, hence `//` comments rather
// than `//!`) and the runtime (`mod resw`).
// It skips XML comments `<!-- -->` (the ResX header contains `<data>`
// examples inside a comment) and decodes standard XML entities as well as
// numeric references `&#nnn;` / `&#xhh;`.

/// Extracts the (key, value) pairs from a `.resw` document, in document
/// order. `<data>` elements without a `<value>` are skipped.
pub fn parse_resw(xml: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut i = 0usize;

    while let Some(rel) = xml[i..].find('<') {
        let start = i + rel;
        let rest = &xml[start..];

        // Skip XML comments (the ResX header contains <data> examples that
        // must not be parsed).
        if let Some(after_comment) = rest.strip_prefix("<!--") {
            match after_comment.find("-->") {
                Some(end) => {
                    i = start + 4 + end + 3;
                    continue;
                }
                None => break,
            }
        }

        // <data ...> element (followed by a space or '>').
        let is_data = rest.starts_with("<data")
            && matches!(
                rest.as_bytes().get(5),
                Some(b' ' | b'\t' | b'\r' | b'\n' | b'>')
            );
        if !is_data {
            i = start + 1;
            continue;
        }

        // End of the opening tag.
        let Some(tag_end) = rest.find('>') else { break };
        let tag = &rest[..tag_end];
        if tag.ends_with('/') {
            // Self-closed <data ... />: no value.
            i = start + tag_end + 1;
            continue;
        }

        let name = extract_attr(tag, "name");
        let body_start = start + tag_end + 1;
        let Some(body_len) = xml[body_start..].find("</data>") else {
            break;
        };
        let body = &xml[body_start..body_start + body_len];

        if let Some(name) = name {
            if let Some(vs) = body.find("<value>") {
                let after_value = &body[vs + "<value>".len()..];
                if let Some(ve) = after_value.find("</value>") {
                    out.push((name, unescape_xml(&after_value[..ve])));
                }
            } else if body.contains("<value/>") || body.contains("<value />") {
                out.push((name, String::new()));
            }
        }

        i = body_start + body_len + "</data>".len();
    }

    out
}

/// Extracts the (decoded) value of an `attr="..."` attribute from an
/// opening tag.
fn extract_attr(tag: &str, attr: &str) -> Option<String> {
    let needle = format!(" {attr}=\"");
    let vs = tag.find(&needle)? + needle.len();
    let ve = tag[vs..].find('"')?;
    Some(unescape_xml(&tag[vs..vs + ve]))
}

/// Decodes standard XML entities (`&amp;` `&lt;` `&gt;` `&quot;` `&apos;`)
/// and numeric references (`&#nnn;` / `&#xhh;`). An unknown sequence is
/// left as-is.
pub fn unescape_xml(s: &str) -> String {
    if !s.contains('&') {
        return s.to_string();
    }
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(amp) = rest.find('&') {
        out.push_str(&rest[..amp]);
        let after = &rest[amp + 1..];
        // Entities are short; bound the search for ';' so a literal
        // (malformed) '&' doesn't swallow the rest of the text.
        let semi = after
            .char_indices()
            .take(12)
            .find(|&(_, c)| c == ';')
            .map(|(idx, _)| idx);
        let decoded = semi.and_then(|semi| {
            let entity = &after[..semi];
            let c = match entity {
                "amp" => Some('&'),
                "lt" => Some('<'),
                "gt" => Some('>'),
                "quot" => Some('"'),
                "apos" => Some('\''),
                _ => {
                    let num = entity.strip_prefix('#')?;
                    let code = if let Some(hex) =
                        num.strip_prefix('x').or_else(|| num.strip_prefix('X'))
                    {
                        u32::from_str_radix(hex, 16).ok()?
                    } else {
                        num.parse::<u32>().ok()?
                    };
                    char::from_u32(code)
                }
            };
            c.map(|c| (c, semi))
        });
        match decoded {
            Some((c, semi)) => {
                out.push(c);
                rest = &after[semi + 1..];
            }
            None => {
                out.push('&');
                rest = after;
            }
        }
    }
    out.push_str(rest);
    out
}
